name: C++ Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build
        run: python ./scripts/build.py
        env:
          SRC_DIR: src
          CXXFLAGS: -std=c++17 -O2